development:
  adapter: postgresql
  encoding: unicode
  database: example_endpoint_api_development
  pool: 5

test: &test
  adapter: postgresql
  encoding: unicode
  database: example_endpoint_api_test
  pool: 5

cucumber:
  <<: *test
